language: node_js
node_js:
- '8'
install: yarn install
script:
- yarn test
- "./dapperdox.sh"
deploy:
  provider: heroku
  api_key:
    secure: poZHDY1F/YvEsio+lkN8RPt4+RI8Ubs+v0hKkqXJa6whazR1CGfq3zYHjrnXHL5q2CeposWqLLXMiV+ceZnJTwag9N3hLQGZCpNyqxTXduKblAhhlizJSsrsoFwn6JuQ/NotL0XOZ5vba1rbQc7XRz6tijGyt8v15ibWjGqWMBDhiTVLhlqGVwPImw6+7904Aw/xgTIvtDjF9UqdrCCUvfmHUt6Phsmsd7xr8J8ljGasFseqX0lmbPeIcO9xUvulkW8uNMJ16c/ieA7gwjHPul3HkIDdKNDqwotB/MfpoFktPYLokvZNkYkaMnUGsIPdCP6K4a5eDnTLIwgMiEfa1E48erBW4nvsNsT8GRYXR4AO6DSk1M5kjSzQlHw4l60+2X5+HORG8mdavy8m9C0P63xgIRooTMVFxIaGoE2ZGYuNr2ZgLMmFcFjCo8QM9RW3MyCB2HzKHnLFq70+/JWYkJXY/T3vqw7qfNDEHRXRV5St65aZBkPyzOMRusIIruvhGxfz5G1JHDX4awAnnrsf7CD0C7sXAUsoF36JVlcOmn6+QMmUOKzmQhi/ciBQRF7nvqfvwnxRX0I+V/OZp1ofFrLbni1W2y18zXhkcBjaLA7uZT6CPj2Ic1PWQbvk6uc7rN8UgrjeFUjyPj7RrqrIlkFqnBDfhjBbiKtk2ykc1xc=
  app: uwa-model
  skip_cleanup: true
  on: master
